version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    working_directory: ~/wordrate
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Restore packages
          command: dotnet restore Wordrate/Wordrate.sln
      - run:
          name: Build solution
          command: dotnet build -c Release Wordrate/Wordrate.sln
      - run:
          name: Publish Api
          command: dotnet publish -c Release Wordrate/WordrateApi/WordrateApi.csproj
      - persist_to_workspace:
          root: .
          paths:
            - Wordrate/WordrateApi/bin/Release/netcoreapp3.0/publish
  deploy:
    machine:
      enabled: true
    working_directory: ~/wordrate
    steps:
      - add_ssh_keys:
          fingerprints:
            - "47:98:40:00:36:8a:48:d8:3d:e9:1a:4f:9c:da:b6:f0"
      - attach_workspace:
          at: ~/wordrate            
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: 'sudo scp -i ~/.ssh/id_rsa_47984000368a48d83de91a4f9cdab6f0 -P 7822 -r Wordrate/WordrateApi/bin/Release/netcoreapp3.0/publish/* $SSH_USER@$SSH_HOST:$APP_DIR'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master